version: "3.8"
services:
  receiver:
    labels:
      kompose.service.type: LoadBalancer
    build: ./receiver
    # image: receiver
    expose:
      - 9988
    ports:
    - "8899:8899"
    environment:
    - DEPLOY_ENVIRONMENT=compose
  emitter:
    # image: emitter
    build: ./emitter
    environment:
    - DEPLOY_ENVIRONMENT=compose
