apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: receiver
  name: receiver
spec:
  # type: NodePort
  ports:
    - name: "8899"
      port: 8899
      targetPort: 8899
    - name: "9988"
      port: 9988
      targetPort: 9988
  selector:
    io.kompose.service: receiver
status:
  loadBalancer: {}
