apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: emitter
  name: emitter
spec:
  replicas: 5
  selector:
    matchLabels:
      io.kompose.service: emitter
  template:
    metadata:
      labels:
        io.kompose.service: emitter
    spec:
      containers:
        - image: emitter 
          imagePullPolicy: Always
          env:
            - name: TARGET_HOST
              value: receiver
          name: emitter
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
