apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: wordhandler
resources:
- emitter
- receiver

images:
- name: emitter
  newName: ghcr.io/felixlut/wordhandler/emitter
  newTag: latest
- name: receiver
  newName: ghcr.io/felixlut/wordhandler/receiver
  newTag: latest
