apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: wordhandler
resources:
- emitter
- receiver
- cli

images:
- name: emitter
  newName: ghcr.io/felixlut/wordhandler/emitter
  newTag: v1.36
- name: receiver
  newName: ghcr.io/felixlut/wordhandler/receiver
  newTag: latest
- name: cli
  newName: ghcr.io/felixlut/wordhandler/cli
  newTag: latest
