commonLabels:
  app: wordhandler
resources:
- emitter-deployment.yaml
- receiver-deployment.yaml
- receiver-service.yaml
- regcred-secret.yaml
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml
- tcp-service.yaml # TODO: Should be a patch
patches:
- ingress-nginx-controller-patch.yaml
