apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: receiver
  name: receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: receiver
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: receiver
    spec:
      containers:
        - image: ghcr.io/felixlut/wordhandler/receiver:kubernetes
          imagePullPolicy: Always
          env:
            - name: DEPLOY_ENVIRONMENT
              value: kubernetes
          name: receiver
          ports:
            - containerPort: 8899
            - containerPort: 9988
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
