apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJabVZzYVhoc2RYUTZaMmh3WDFCS1dtWnJRVzFuYmpkSk4xTndTRk4xYmxGSllrdE5Rbmd5YVdsa1V6QndlWGxKUlE9PSIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlptVnNiSFYwT2tadmRHSmhjMnRsZERFd0lRPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson