apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec: 
  template:
    spec:
      containers:
      - name: controller
        args: # Copy pasted from minikube since arrays cant be merged easily (see https://github.com/kubernetes-sigs/kustomize/issues/3265)
        # TODO: Append tcp-services-configmap instead of brute force copy paste...
        - /nginx-ingress-controller
        - --election-id=ingress-controller-leader
        - --controller-class=k8s.io/ingress-nginx
        - --watch-ingress-without-class=true
        - --ingress-class=nginx
        - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services # The only one we want
        - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
        - --validating-webhook=:8443
        - --validating-webhook-certificate=/usr/local/certificates/cert
        - --validating-webhook-key=/usr/local/certificates/key
        - --default-ssl-certificate={{ .CustomIngressCert }}
        ports:
         - containerPort: 8899
           hostPort: 8899
